services:
  3x-ui:
#    image: ghcr.io/mhsanaei/3x-ui:v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3x-ui
    hostname: localhost
    volumes:
      - $PWD/cert/:/root/cert/
    environment:
      - DATABASE_URL=host=db user=postgres password=postgres dbname=x_db port=5432 sslmode=disable
      - PWD=${PWD}
    tty: true
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: external-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: x_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres" ]  # Проверка доступности базы данных
      interval: 10s  # Периодичность проверки
      retries: 3      # Сколько раз проверять, прежде чем считать базу недоступной
      timeout: 5s     # Время ожидания ответа от базы
      start_period: 30s # Время ожидания до начала проверки

volumes:
  postgres_data:
